services:
  vscode:
    build: .
    image: vscode-server
    container_name: vscode-server
    hostname: server
    restart: always
    user: "${UID}:${GID}"
    ports:
      - 5555:5555
    volumes:
      - $HOME:/home/vscode:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
